algo = input('Escreva algo: ')

print(algo, 'O tipo é: ', type(algo))
print(algo, 'Tem numeros?: ', algo.isnumeric())
print(algo, 'Tem letras?: ', algo.isalpha())
print(algo, 'Tem letras e numeros?: ', algo.isalnum())
print(algo, 'Tem numeros de 0 a 9?: ', algo.isdecimal())
print(algo, 'Possui todos as palavras em minúsculo?: ', algo.islower())
print(algo, 'Possui espaços apenas espaços em branco?: ', algo.isspace())
print(algo, 'Possui apenas letras maiúsculas?: ', algo.isupper())
print(algo, 'Possui a primeira palavra maiúscula e o restante minúsculas?: ', algo.istitle())